baseURL = "https://shivanguniyal-polcon.github.io/"
languageCode = "en-us"
title = "Shivang Uniyal"
theme = "hugo-coder"
paginate = 10

[params]
  author = "Shivang Uniyal"
  info = ["Policy Consultant", "Data & Tech Strategist"]
  description = "Shivang Uniyal's personal portfolio and policy consulting hub."
  keywords = "policy,consultant,political,data,portfolio"
  avatarURL = "/images/avatar.jpg"
  colorScheme = "auto"
  hidecolorschemetoggle = false
  customCSS = ["css/custom.css"]

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/shivanguniyal-polcon/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/shivang-uniyal/"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"

[[menu.main]]
  name = "Still Learning"
  weight = 3
  url = "learning/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
